feat(common):added new component years button[SEM-09]
Ditmar/sem_2023_magazine pull request #7
Opened 2023-12-08 07:14 UTC by 9lnmune9

Added new component years button and filter for years

![Volumens_Button Anios](https://github.com/Ditmar/sem_2023_magazine/assets/145077905/59df183f-b554-4821-a8a5-6cde3288805e)
![FilterAnios](https://github.com/Ditmar/sem_2023_magazine/assets/145077905/07078a29-023a-45ac-afa0-68e0705ba2d3)
![FilterAnios2](https://github.com/Ditmar/sem_2023_magazine/assets/145077905/569e43e2-87e7-41f7-8077-51c492303857)

2023-12-08 10:07 UTC, olmedo90 commented
![image](https://github.com/Ditmar/sem_2023_magazine/assets/77794323/5ffd84f7-1fcf-453b-b73c-d5782096ebdc)
It is according to the figma, continue with the same interest.
👍👍👍

2023-12-08 21:04 UTC, Ditmar requested changes
good work! please review the few comments, and you can get the approve in this pr

2023-12-08 21:04 UTC, Ditmar commented on src/app/volumenes/[dateYear]/page.tsx
> +      <div className="flex min-h-screen flex-col items-center justify-between p-24">
please fragment, your components, into small parts. 
you can divide this part of your code and create a component called `ItemVolumes`

2023-12-08 21:04 UTC, Ditmar commented on src/app/volumenes/[dateYear]/page.tsx
> +              <h3 className="text-xl font-bold">
The same here is important to divide your code an create a reusable components

2023-12-08 21:04 UTC, Ditmar commented on src/app/volumenes/page.tsx
> +import volumenes from "@/data/Volumenes"
please use simple quotes

2023-12-08 21:04 UTC, Ditmar commented on src/app/volumenes/page.tsx
> +import Volume from "./[dateYear]/page"
use simple quotes

2023-12-11 22:23 UTC, Ditmar approved these changes
Approved good job

2023-12-11 22:23 UTC, merged